/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Mostra_Detalle_Factura_Compra extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios_Tabla
     */
    public Mostra_Detalle_Factura_Compra() {
        initComponents();
    }

    public JTable getJtDetalleFactura() {
        return jtDetalleFactura;
    }

    public JLabel getTxtcomprobante() {
        return txtcomprobante;
    }

    public void setTxtcomprobante(JLabel txtcomprobante) {
        this.txtcomprobante = txtcomprobante;
    }

    public JLabel getTxtfactura() {
        return txtfactura;
    }

    public void setTxtfactura(JLabel txtfactura) {
        this.txtfactura = txtfactura;
    }

    public JLabel getTxtfecha() {
        return txtfecha;
    }

    public void setTxtfecha(JLabel txtfecha) {
        this.txtfecha = txtfecha;
    }

    public JLabel getTxtimpuesto() {
        return txtimpuesto;
    }

    public void setTxtimpuesto(JLabel txtimpuesto) {
        this.txtimpuesto = txtimpuesto;
    }

    public JLabel getTxtproveedor() {
        return txtproveedor;
    }

    public void setTxtproveedor(JLabel txtproveedor) {
        this.txtproveedor = txtproveedor;
    }

    public JLabel getTxttipopago() {
        return txttipopago;
    }

    public void setTxttipopago(JLabel txttipopago) {
        this.txttipopago = txttipopago;
    }

    public JLabel getTxtusuario() {
        return txtusuario;
    }

    public void setTxtusuario(JLabel txtusuario) {
        this.txtusuario = txtusuario;
    }

    public JLabel getTxtvalorpagar() {
        return txtvalorpagar;
    }

    public void setTxtvalorpagar(JLabel txtvalorpagar) {
        this.txtvalorpagar = txtvalorpagar;
    }

    
    
    public void setJtDetalleFactura(JTable jtDetalleFactura) {
        this.jtDetalleFactura = jtDetalleFactura;
    }

   

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalleFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblproveedor = new javax.swing.JLabel();
        lbltipopago = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblcomprobante = new javax.swing.JLabel();
        txtfactura = new javax.swing.JLabel();
        txtproveedor = new javax.swing.JLabel();
        txttipopago = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        txtusuario = new javax.swing.JLabel();
        txtcomprobante = new javax.swing.JLabel();
        lblimpuesto = new javax.swing.JLabel();
        txtimpuesto = new javax.swing.JLabel();
        lblvalorpago = new javax.swing.JLabel();
        txtvalorpagar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        lblTitulo.setText(" Detalle Factura");

        jtDetalleFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtDetalleFactura);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("factura");

        lblproveedor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblproveedor.setText("Proveedor");

        lbltipopago.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbltipopago.setText("Tipo de Pago");

        lblfecha.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblfecha.setText("fecha");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        lblcomprobante.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblcomprobante.setText("Comprobante");

        txtfactura.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        txtproveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtproveedor.setText("jLabel3");

        txttipopago.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txttipopago.setText("jLabel2");

        txtfecha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtfecha.setText("jLabel2");

        txtusuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtusuario.setText("jLabel2");

        txtcomprobante.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtcomprobante.setText("jLabel2");

        lblimpuesto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblimpuesto.setText("Impuesto");

        txtimpuesto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtimpuesto.setText("jLabel2");

        lblvalorpago.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblvalorpago.setText("Valor A Pagar");

        txtvalorpagar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtvalorpagar.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblproveedor)
                            .addComponent(lbltipopago))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfecha)
                            .addComponent(lblUsuario)
                            .addComponent(lblcomprobante)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcomprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(148, 148, 148))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblvalorpago)
                    .addComponent(lblimpuesto))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtimpuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(txtvalorpagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblfecha)
                    .addComponent(txtfactura)
                    .addComponent(txtfecha))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblproveedor)
                    .addComponent(lblUsuario)
                    .addComponent(txtproveedor)
                    .addComponent(txtusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipopago)
                    .addComponent(lblcomprobante)
                    .addComponent(txttipopago)
                    .addComponent(txtcomprobante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimpuesto)
                    .addComponent(txtimpuesto))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblvalorpago)
                    .addComponent(txtvalorpagar))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDetalleFactura;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblcomprobante;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblimpuesto;
    private javax.swing.JLabel lblproveedor;
    private javax.swing.JLabel lbltipopago;
    private javax.swing.JLabel lblvalorpago;
    private javax.swing.JLabel txtcomprobante;
    private javax.swing.JLabel txtfactura;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JLabel txtimpuesto;
    private javax.swing.JLabel txtproveedor;
    private javax.swing.JLabel txttipopago;
    private javax.swing.JLabel txtusuario;
    private javax.swing.JLabel txtvalorpagar;
    // End of variables declaration//GEN-END:variables
}
